name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.115.4
    steps:
      - name: Install Hugo CLI
        uses: actions/setup-hugo@v1
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          
      # If you still need Dart Sass, you can add the installation step here.

      - name: Checkout
        uses: actions/checkout@v2  # You can keep this if your theme is a submodule.

      - name: Install Node.js dependencies
        run: npm ci
      
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: hugo --gc --minify --baseURL "${{ github.server_url }}/${{ github.repository }}/"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: ./public

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: public

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Push to gh-pages
        run: |
          cd public
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch -M gh-pages
          git remote add origin "https://github.com/${{ github.repository }}.git"
          git push -f origin gh-pages
